<?php
/**
 * BelVG LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 *
 ********************************************************************
 * @category   BelVG
 * @package    BelVG_GuestWishlist
 * @copyright  Copyright (c) BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php $helper = $this->helper('\BelVG\GuestWishlist\Helper\Data');?>

<?php if ($helper->isEnabled()):?>
    <script type="text/x-magento-init">
        {
            "*": {
                "guestwishlist": {
                    "wishlistUrl": "<?php echo $helper->getWishlistUrl()?>"
                }
            }
        }
    </script>
<?php endif; ?>
